
#
#	TODO : include cross-compile etc.
#
#	TODO : handle cross compile, library generation etc.

# CROSS = arm-none-eabi-

#
#

SRC = main.c 

#SRC += c/c.c

SRC_CC = lock.cpp mutex.cpp test.cpp

APP = maker

LIBS = pthread stdc++

#DEFINES = DEBUG

-include build.mk

# 	FIN
